### ISSUE TITLE
Paper Request

### ISSUE THREAD

**Issue by ErnestoHrs** [18heweng666/DDPG-GCN-for-bidding-strategy#2]
Hi,18heweng666. I can not find your paper "Optimizing bidding strategy in electricity market based on graph convolutional neural network and deep reinforcement learning" in Google Scholar. Could you please upload this paper in Gtihub? Thank you!

**Comment by 18heweng666** [comment]
Hi, thank you for your interest in our work. The paper is scheduled for publication soon. Please stay tuned for updates on this repository.

**Comment by ErnestoHrs** [comment]
> Hi, thank you for your interest in our work. The paper is scheduled for publication soon. Please stay tuned for updates on this repository.

Ok, thank you!
